apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${SA_NAME}-to-clusterrole-namespaced-admin
  name: $NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespaced-admin
subjects:
- kind: ServiceAccount
  name: $SA_NAME
  namespace: $SA_NAMESPACE