apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-appslogs
spec:
  version: 7.13.3
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-logging
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            # Change storage size based on need
            storage: 5Gi
        # Change ClassName
        storageClassName: local-path
    podTemplate:
      spec:
        # Change tolerations and node selector based on needs
        tolerations:
        - key: "role"
          operator: "Equal"
          value: "logging-monitoring"
          effect: "NoSchedule"
        nodeSelector:
          role: logging-monitoring
        containers:
        - name: elasticsearch
          # Change resources
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "2Gi"
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms1g -Xmx1g"
