apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: $NAMESPACE
spec:
  limits:
  - max:
      cpu: "4000m"
      memory: "8Gi"
    min:
      cpu: "100m"
      memory: "99Mi"
    # No overcommitment
    maxLimitRequestRatio:
      memory: 1
      cpu: 1
    type: Pod